- manifests/resources/relay.sh_tenants.yaml
- manifests/resources/relay.sh_webhooktriggers.yaml
- pkg/apis/relay.sh/v1beta1/tenant_types.go
- pkg/apis/relay.sh/v1beta1/trigger_types.go
- pkg/controller/handler/enqueue_namelabel.go
- pkg/controller/trigger/controller.go
- pkg/errmark/errmark.go
- pkg/errmark/transient.go
- pkg/model/model.go
- pkg/obj/tenant.go
- pkg/obj/tenantdeps.go
- pkg/obj/util.go
- pkg/obj/webhooktrigger.go
- pkg/obj/webhooktriggerdeps.go
- pkg/reconciler/tenant/reconciler.go
- pkg/reconciler/trigger/reconciler.go
- tests/e2e/tenant_test.go
- tests/e2e/utils_test.go
- tests/e2e/webhooktrigger_test.go
This change adds a number of safeguards to ensure tenants and webhook triggers clean up stale data. Namely:
- When a tenant namespace changes, the tenant now deletes the old namespace (if managed) before creating the new namespace.
- Tenant existence is no longer a prerequisite for deleting a webhook trigger.
- When a tenant namespace changes, the webhook trigger now updates its configuration to create a new Knative service in the new namespace.
> Propagate tenant changes to dependent objects

- manifests/resources/nebula.puppet.com_workflowruns.yaml
- pkg/apis/nebula.puppet.com/v1/types.go
- pkg/apis/nebula.puppet.com/v1/zz_generated.deepcopy.go
- pkg/manager/builder/metadata.go
- pkg/manager/configmap/environment.go
- pkg/manager/memory/environment.go
- pkg/manager/reject/environment.go
- pkg/metadataapi/opt/sample.go
- pkg/metadataapi/sample/auth.go
- pkg/metadataapi/server/api/environment.go
- pkg/metadataapi/server/api/environment_test.go
- pkg/metadataapi/server/api/server.go
- pkg/metadataapi/server/middleware/auth.go
- pkg/model/environment.go
- pkg/model/model.go
- pkg/obj/configmap.go
- tests/e2e/workflowrun_test.go
Introduces basic Metadata API endpoints and processing for handling environment variables. The processing is similar to specification handling, with a few deviations.
Initially supports the use of parameters, secrets, and outputs. Of particular note is that this cannot resolve connection-related data due to the current implementation of connections. Any necessary rework/refactor of connections will happen at an unspecified point in the future.
Further use of this support (i.e. automatically setting environment variables based on this data) will be added incrementally and independently.
> Initial environment variable support

- pkg/obj/workflowrun.go
- pkg/reconciler/workflow/reconciler.go
- tests/e2e/workflowrun_test.go
Automatically complete a workflow run without steps, avoiding the unnecessary creation of any associated Tekton artifacts.
> Handle workflow runs without steps

- cmd/relay-operator/main.go
- pkg/config/config.go
- pkg/model/model.go
- pkg/obj/knativeservice.go
- pkg/obj/task.go
- pkg/obj/tenant.go
- pkg/obj/tenantdeps.go
- pkg/reconciler/tenant/reconciler.go
- tests/e2e/tenant_test.go
Adds initial handling of tool injection. Currently expands the tenant reconciler directly to layer on support in a limited fashion. In the future, this may be collapsed into the tenant dependencies in a cleaner manner.
- Tool injection status is being derived from the job status directly; this needs smoothed over.
- Workflow runs cannot load the tenant reference currently; this is being temporarily worked around.
- Does not handle updates to the tool injection image.
- Does not cleanup the original PVC used for the initial write access.
- Does not cleanup any jobs related to creation of the PVCs.
- Only supports GCE and Hostpath currently (and is essentially hardcoded).
> Initial tool injection handling

- pkg/authenticate/kubernetes.go
Prevent eventual consistency issues when validating a pod during authentication.
> Add retry logic for pod validation

- go.mod
- go.sum
- pkg/metadataapi/server/api/validate.go
- pkg/metadataapi/server/api/validate_test.go
This commit changes the error type comparison logic to use errors.As
instead of errors.Is, which fixes the issue where
SchemaDoesNotExistError was being captured and sent to the monitoring
backend.
> fixes the error type comparison when validating schemas

- cmd/relay-runtime-tools/runner.go
- go.mod
- go.sum
Sends the timestamp as part of log message. Previously this was only being set downstream, which can lead to inaccuracy and drift.
> Send timestamp as part of log message

- hack/kind-ci/Dockerfile
This is a temporary workaround to restore functional Integration Testing to Relay Core.
This temporarily avoids GVisor version 20201208.0 (which includes containerd version 1.3.9).
A few relevant links:
- https://github.com/google/gvisor/compare/release-20201130.0...release-20201208.0
- https://github.com/containerd/containerd/releases/tag/v1.3.9
- https://github.com/google/gvisor/commit/9eb77281c4fe1c1f252a0df67ca2c1fee8867b80
- https://github.com/containerd/containerd/security/advisories/GHSA-36xw-fx78-c5r4
- https://nvd.nist.gov/vuln/detail/CVE-2020-15257
> Use last known working version of GVisor runsc

- cmd/relay-runtime-tools/main.go
- go.sum
- pkg/entrypoint/runner.go
- pkg/entrypoint/runner_test.go
- Added handling of some 5xx response status codes for the retry logic. We're seeing a mixture of both outright errors and 500s in our environments currently.
- Unfortunately, due to the number of integration tests that utilize the entrypointer without an actual Metadata API to access, large timeout values break the current tests. This will need a better solution in the future, but for now, this attempts to define reasonable default timeouts that will still be effective in live environments (which will be thoroughly tested for efficacy).
> Add retry logic for 5xx status codes

- pkg/expr/evaluate/errors.go
- pkg/expr/evaluate/evaluate.go
- pkg/expr/evaluate/evaluate_test.go
- pkg/expr/evaluate/select.go
- pkg/expr/fnlib/path.go
- pkg/expr/fnlib/path_test.go
- pkg/expr/model/result.go
Function evaluation does not work appropriately with data-oriented evaluables/resolvables (i.e. !Connection, !Secret, !Output, etc.).
Essentially, functions are currently expecting arguments to be fully resolvable at all times when called, and this is not how our system (or the evaluation functionality) works. Functions have to operate the same as any other element and defer processing when used in conjunction with other unresolvables.
This applies most significantly to !Fn.path at the moment, as this is currently the most labor intensive function, but this is a general problem that needs to be fixed before it becomes worse.
We have several different design updates planned (for both the evaluation in general, and the language being used) and this overall functionality is likely to be …
> Improve function evaluation

- pkg/workflow/types/v1/decoder.go
- pkg/workflow/types/v1/decoder_test.go
- pkg/workflow/types/v1/testdata/valid.yaml
- pkg/workflow/types/v1/types.go
- pkg/workflow/types/v1/webhooktriggermapping.go
- pkg/workflow/types/v1/webhooktriggermapping_test.go
- pkg/workflow/types/v1/workflowrunmapping.go
- pkg/workflow/types/v1/workflowrunmapping_test.go
Environment variable handling was added to Relay API prior to this code being copied into Relay Core, but the changes happened at roughly the same time and were not integrated. One of the many dangers of having duplicated code.
> Add environment to workflow types

- pkg/operator/admission/podenforcement.go
- pkg/operator/admission/volumeclaim.go
Most fields of a pod are immutable after creation, so if you change the configuration (e.g., enabling sandboxing) in the middle of a workflow run, the pods that have the old configuration will get stuck in an update loop that will cause them to sit around waiting forever.
> Only attempt to enforce pod requirements during the creation phase

- pkg/workflow/types/v1/enginemapping.go
- pkg/workflow/types/v1/tenantmapping.go
- pkg/workflow/types/v1/webhooktriggermapping.go
Removes name-based labels (as labels have strict naming requirements). We don't want to have a requirement that these are sanitized, for a variety of reasons. We do not currently use these labels anywhere. Trigger names are already available as part of the `WebhookTrigger` spec, additionally.
> Remove name-based labels

- go.mod
- go.sum
- manifests/resources/role.yaml
- pkg/install/config/rbac/role.yaml
- pkg/install/controller/operatorstate.go
- pkg/install/controller/relaycorecontroller.go
- pkg/install/controller/vaultagentstate.go
- scripts/build
* Removes legacy RBAC permissions (PVs, PVCs, Jobs)
* Adds new PVPool Checkout RBAC permissions
* Adds Knative Revisions RBAC permissions
* Removes legacy `-tool-injection-image` configuration option (preventing the dev environment from functioning).
* Adds missing (but unused) setting for optional manual configuration of the LogService vault role
> Fix RBAC permissions for relay-installer

- pkg/expr/evaluate/mapping.go
- pkg/expr/model/errors.go
- pkg/expr/model/result.go
- pkg/expr/model/result_json.go
- pkg/expr/pathlang/adapter.go
- pkg/expr/resolve/noop.go
It turns out that we actually need specific data (not the query itself) to be unresolvable so that we can validate the structure of a workflow without event data being passed in to it. This change brings back the unresolvable field and adds a NoOpDataTypeResolver that always returns a not found error.
> Bring back unresolvable data to improve validation

- pkg/workflow/asset/data/schemas/v1/Workflow.json
The Relay Operator purposefully marks workflow runs as **Complete** if no steps are received. This is particularly useful when testing triggers that do not have or need steps yet.
Unfortunately, this now breaks due to Workflow schema validation requiring at least one step.
With planned workflow execution changes, steps will not be required soon regardless.
> Do not require workflow steps

- cmd/relay-operator/main.go
- pkg/operator/config/config.go
- pkg/operator/reconciler/trigger/reconciler.go
- pkg/operator/reconciler/workflow/reconciler.go
- tests/e2e/e2econfig_test.go
Splits the tool injection pool configuration into two different separate options for triggers and workflows. The same pool can be used for both if desired.
Trigger pods do not change with the same frequency as workflows. Particularly when disabling scale-to-zero.
Having a separate, more static pool for triggers will make it easier to maintain and manage the more volatile workflow pool, as it constantly changes as workflow runs are initiated.
Additionally, as part of short-term improvements to workflow start time, the workflow pool will be disabled (soon) and the trigger pool will remain as-is in order to ensure trigger logs are captured.
> Split tool injection pools

- pkg/manager/configmap/stepoutput.go
- pkg/manager/configmap/stepoutput_test.go
- pkg/manager/memory/stepoutput.go
- pkg/manager/reject/stepoutput.go
- pkg/model/stepoutput.go
- pkg/operator/app/workflowrun.go
Refactors the existing `StepOutputManager` slightly. Adds a new `ListSelf` function to make it easier to list outputs for the constructed step. A larger refactor/redesign is probably warranted in the future.
`NewStepOutputManager(step *model.Step, cm ConfigMap)` requires a step to be passed in, but this is used inconsistently.
It is required in some cases, but for the `List` function, it is ignoring the step name, and returning all outputs for all steps instead. It uses the `Run` property from the `Step`, but only to pass back as part of the Step data from all steps. Ideally, we update this handling for both consistency.
> Add additional function to list outputs by step

- pkg/operator/app/networkpolicy.go
Note that this filter applies to inter-pod or pod-to-host networking, not intra-pod networking. I.e., it is still possible to communicate with network servers running in different containers in the same pod.
> Add 127.0.0.0/8 to bogon filter

- tests/e2e/workflowrun_test.go
Use unique workflow name in gVisor test cases
> Use unique workflow name in gVisor test cases

- .github/workflows/ci.yaml
- hack/k3s/config-v1.19.toml.tmpl
* Pin gVisor version to `20211019` for CI testing
* [20211026](https://github.com/google/gvisor/compare/release-20211019.0...release-20211026.0) breaks CI (potentially due to the update to support containerd 1.5)
* Update to the latest k3s images
* Strictly unnecessary, but always better to take the opportunity to upgrade
* Migrate the containerd config to version 2
* Unnecessary, but new options will only be supported in version 2, and documentation is starting to trend towards version 2 configurations (i.e. https://github.com/containerd/containerd/blob/main/docs/cri/config.md)
* (some of these options are now deprecated, but leaving them for now...)
> Updating gVisor handling in CI

- .github/workflows/ci.yaml
The latest version of Calico ([v3.21](https://github.com/projectcalico/calico/releases/tag/v3.21.0)) does not function within our testing environment. The exact cause has not yet been determined.
This update pins Calico to version 3.20 in order to unblock development.
Also updates k3s versions to the latest (although strictly unnecessary to this fix).
> Pin specific Calico version

- pkg/operator/reconciler/run/reconciler.go
Avoid (legacy) log handling when pods are never created.
This technically does not cause any harm other than spurious errors.
TaskRuns may complete without a valid pod ever being created (in rare cases of critical failure).
> Do not log when no pod is available

- pkg/model/model.go
- pkg/operator/app/task.go
Adds a default command for approvals.
The fake step that approvals currently require was previously running without a command. This would just exit without doing anything. (Noting that this requires a not-insignificant amount of time for no purpose, so it's not the best strategy for overall performance either...)
This no longer works with the version of Tekton we are using, as not providing a command causes internal Tekton errors when handling TaskRuns.
In this case, we need an innocuous command to execute that does not add additional processing time (and avoids any sensitive information from being exposed to the pod logs).
NOTE: The current approach to _legacy_ approvals should be considered deprecated. The current condition handling is likely going to be completely removed in the very …
> Add default command for approvals

- pkg/metadataapi/server/api/conditions.go
- pkg/metadataapi/server/api/conditions_test.go
Fixes another outstanding known issue with approvals (approvals can hang when combined with conditions even though the condition is known to be false - and it's still waiting on approval anyway).
Builds on the logic added previously, which allows this to be fixed easier.
NOTE: This overloads the meaning of "Resolved" in a potentially confusing way. Resolved in this sense is not specifically equivalent to the expression resolution.  All of this logic is going to be refined (or removed) in the near future as we migrate the overall condition logic.
> Improved approvals with when conditions

- pkg/manager/configmap/stepoutput.go
- pkg/manager/configmap/stepoutput_test.go
- pkg/manager/memory/stepoutput.go
- pkg/manager/reject/stepoutput.go
- pkg/metadataapi/server/api/outputs.go
- pkg/metadataapi/server/api/outputs_test.go
- pkg/metadataapi/server/api/server.go
- pkg/model/stepoutput.go
Initial changes for step output sensitivity.
Allows setting step output `metadata` in addition to setting output values.
This was determined to be the best design given the way we set set values (rather than rewrite and break backwards compatibility).
Currently, the `sensitive` field is the only option, but this is purposefully built to be expansive in case other settings are needed in the future.
> Add step output metadata

- pkg/install/app/metadataapideps.go
- pkg/install/app/operatordeps.go
- pkg/install/app/webhookcertificatecontrollerdeps.go
Splits `Ownables`/`Persisters` for dependencies with mixed usage. A better pattern for this (without requiring duplication) would probably be ideal in the future.
In this case specifically, removes `ClusterRole`, `ClusterRoleBinding`, and `MutatingWebhookConfiguration `from the list of `Ownables`.
> Avoid ownership of non-ownable dependencies

- pkg/install/app/coredeps.go
If the `relay-system` namespace already exists, the Relay installer would continuously error out at the start of reconciliation.
(The Relay dev environment would have already created it, for example; this may change in the future if we fold that logic directly into the Relay installer, but it's likely fair to assume it may have already been validly created beforehand...)
We may want to consider adding an optional flag to the `Persist` handling somewhere to better support this, similar to how we currently have `GetIgnoreNotFound` and `DeleteIgnoreNotFound` to obfuscate/wrap similar functionality.
> Support relay-system namespace existing

- pkg/install/app/coredeps.go
- pkg/install/reconciler/reconciler.go
Small tweaks to error logging.
- Cleans up a few redundant `ApplyCoreDeps` error logs (that were already being logged in the install reconciler, which is preferable).
- Added one missing error log to the install reconciler.
> Cleanup error logging

- pkg/install/app/webhookcertificatecontroller.go
Slight adjustment to the name of the webhook service name used in the Relay Installer to match the service created.
> Fix webhook service name used in installer

- pkg/install/app/logservicedeps.go
- pkg/install/app/metadataapideps.go
- pkg/install/app/operatordeps.go
- pkg/install/app/vaultconfigdeps.go
- pkg/install/app/webhookcertificatecontrollerdeps.go
For all of the Installer dependency objects, `Core` is passed into the respective `New` functions and does not need to be loaded again in every `Load` call.
The expectation is that `Core` would have been appropriately loaded prior to calling the various `New` functions (with a static spec that would not be changing from dependency to dependency, and should not need reloading). Further, it would not be considered appropriate use to only initialize the `client.ObjectKey` and require downstream loading in every dependency object (even if using a dependency class in a standalone manner).
Filed under code cleanliness / standards.
> Remove unnecessary core load calls

- cmd/relay-installer/main.go
- cmd/relay-metadata-api/main.go
- cmd/relay-operator/main.go
- go.mod
- go.sum
- pkg/operator/reconciler/tenant/reconciler.go
Adds the Passthrough alerts delegate as a default (if Sentry is not configured); this logs captured error information by default in any environment without Sentry (i.e. local dev environments or other test environments).
> Add default (passthrough) alerts delegate

- pkg/install/app/clusterrole.go
- pkg/install/app/metadataapideps.go
- pkg/install/app/operatordeps.go
For a standalone operator deployment, bind the delegate ClusterRole to the service account to provide all necessary RBAC permissions.
The method used in production is not currently available via this repository.
(we may or may not change that in the future...)
> (Easier) Operator RBAC standalone support

- pkg/install/app/vaultengineconfigdeps.go
- pkg/install/vault/init.go
The Log Service is an optional component of the Relay Installer. Continue this pattern to ensure that the Log Service vault configuration is also optional.
NOTE: Currently the vault configuration data is inconsistently organized across multiple objects, but any change to this organization will be done at a later time.
> Log service vault config is now optional

- examples/install/relaycore.yaml
Adds the LogService to the default RelayInstaller example (defaults to the new in memory option that is now available).
> Add LogService to RelayInstaller example

- cmd/relay-operator-vault-init/main.go
- cmd/relay-operator-vault-init/wire.go
- cmd/relay-operator-vault-init/wire_gen.go
- pkg/install/op/kube/kube.go
- pkg/install/vault/init.go
Improved `wire` handling for vault initialization.
Previously `wire` was only be used to handle the vault client, but it is now initializing the entire vault initialization stack.
> Update wire handling for vault init

- pkg/manager/memory/stepmessage.go
- pkg/metadataapi/sample/auth.go
- pkg/metadataapi/server/api/validate.go
- pkg/metadataapi/server/api/validate_test.go
Validation errors are now being reported via step messages.
* Removes the Sentry alerts for schema validation
* Adds an in-memory option for step messages
* Updates tests to use the in-memory option
> Do not send validation alerts to Sentry

- .ko.yaml
Modifies base image for `relay-operator` to `gcr.io/distroless/static:latest`.
> Modify base image for relay-operator (ko)

- .ko.yaml
- scripts/build
As an initial transition to using `ko` for the runtime tools, use the existing `relaysh/relay-runtime-tools` as the base.
> Use ko for runtime tools (temporary base during transition)

- pkg/model/model.go
- pkg/operator/app/knativeservice.go
- pkg/operator/app/task.go
Switch entrypoint to `ko` path.
Currently this renames the executable to the currently expected `entrypoint` command.
May change this when we enhance the command support (soon).
> Switch entrypoint to ko path

- pkg/manager/service/log.go
Remove disruptive forced timeouts during logging.
The original intention was to prevent any single log message from causing too much delay if BigQuery was slow to respond (as it does rarely), but this is causing more harm than good.
Particularly with retry logic in place, as under load this can constantly cause prematurely aborted connections.
This system will be replaced in the next phase of log handling.
> Remove disruptive forced timeouts during logging

- cmd/relay-runtime-tools/main.go
- pkg/entrypoint/cmd/cmd.go
- pkg/entrypoint/cmd/initialize.go
- pkg/model/model.go
- pkg/util/file/file.go
Adds entrypoint initialization.
Currently unused; subsequent phased deployments are ready to deploy incrementally to ensure no production steps fail during the brief transition from one system to another.
This allows the use of a fully `distroless` base by removing the need for the `cp` command.
Currently uses rudimentary command logic, which may be replaced with a more robust system later.
> Add entrypoint initialization

- pkg/entrypoint/runner.go
- pkg/model/model.go
- pkg/operator/app/knativeservice.go
- pkg/operator/app/task.go
Using `input` for steps allows free-form use without any real restriction, and we can't really make a judgement call about whether the schema fields are necessary or not. Given that we consider this (essentially) advanced use for advanced users, it's probably sufficient to turn schema validation off completely for this use case.
In the future, we could consider adding more contextual information about whether the schema validation was checked or not, and make this visible via the UI, but that would be over-engineering a solution at this particularly point in time.
> Do not validate schema when using input (script)

- cmd/relay-operator/main.go
- pkg/operator/reconciler/run/reconciler.go
Legacy storage client is now optional. This is going to be removed completely during the next phase of the PLS.
More importantly, this should not be required as part of the `RelayInstaller` functionality, which allows further cleanup of legacy tech debt.
> Legacy storage client is now optional

- pkg/entrypoint/config.go
- pkg/entrypoint/runner.go
- pkg/entrypoint/runner_test.go
- pkg/metadataapi/server/middleware/auth.go
- pkg/model/model.go
- pkg/operator/app/knativeservice.go
- pkg/operator/app/task.go
Enhance the configurability of secure logging (and the entrypointer in general):
* Slightly better approach to disable the PLS for steps temporarily (performance-related)
* Allows easier testing of upcoming PLS changes in the development environment
* The legacy PVC log storage is being removed, and integrating the PLS into the development environment faster is beneficial on multiple levels
* Streamlined entrypointer configuration
Having the capability to configure the entrypointer will likely remain. Much of this code will probably be removed once the PLS is fully integrated, however.
> Expand configuration of secure logging

- examples/install/configmap.yaml
- examples/install/kustomization.yaml
- examples/install/namespace.yaml
- examples/install/relaycore.yaml
- manifests/installer/clusterrole.yaml
- manifests/installer/clusterrolebinding.yaml
- manifests/installer/deployment.yaml
- manifests/installer/serviceaccount.yaml
- pkg/install/app/clusterrole.go
- pkg/install/app/logservicedeps.go
- pkg/install/app/metadataapideps.go
- pkg/install/app/operatordeps.go
- pkg/install/app/rolebinding.go
- pkg/install/app/vaultengineconfigdeps.go
- pkg/install/app/vaultserverbuiltinconfigdeps.go
- pkg/install/app/webhookcertificatecontrollerdeps.go
* The Relay Installer can now install multiple, independent Relay Core systems in separate namespaces (ideally using the new `tenantNamespace` option to differentiate)
* Splits the Relay Installer namespace (`relay-installer`) from the Relay Core namespace (`relay-system`) in the default install example.
* Consistently renames `relay-install-operator` to `relay-installer`.
> Support multiple operator deployments from install

- pkg/manager/configmap/condition_test.go
- pkg/metadataapi/server/api/conditions.go
- pkg/metadataapi/server/api/conditions_test.go
The conditions endpoint no longer considers a `When` condition "not found" as an error state.
The conditions endpoint is currently only being checked when a Tekton `Condition` is present, and therefore is only being validly called when a `When` condition is already known to be present. Tekton is removing `Conditions` soon, and the call to the conditions endpoint is being moved into the Relay entrypointer process. The entrypointer process will call the conditions endpoint universally without being aware of whether a `When` condition is present or not (and applies equally to both `Steps` and `Triggers`).
It is (exceedingly) unlikely that a "not found" state indicates an actual error in this case; and if an error occurs creating the underlying condition, that needs handled with the proper …
> Handle conditions not defined (validly)

- pkg/expr/evaluate/template.go
- pkg/operator/app/configmap.go
Change the step status expression language name from "status" to "steps". In the future, we will move outputs under the "steps" keyword as well.
> Change the step status expression language name

- cmd/relay-operator/main.go
- pkg/operator/dependency/manager.go
Remove legacy metrics server and the old dependency chain entirely. No legacy metrics exist at this time.
Leaving the configuration options intact for backwards compatibility. If `relay-metrics` was ever merged into `relay-operator`, these would be necessary again anyway.
> Remove legacy metrics server

- cmd/relay-metrics/main.go
- manifests/resources/relay.sh_runs.yaml
- pkg/apis/relay.sh/v1beta1/run_types.go
- pkg/metrics/reconciler/run/reconciler.go
- pkg/operator/app/run.go
- pkg/operator/handler/condition/run.go
Removes `TimedOut` as a discrete status (this is already bucketed as a failure, and is unnecessary as a discrete status). If a timed out status were to be added in again, it would be as a reason related to failure and/or system error.
> Remove timed out as a discrete status

- pkg/operator/app/run.go
- pkg/operator/handler/condition/run.go
Run status is now an aggregate status based solely off the step status data (or other internal run status data), which simplifies/solidifies the processing, provides more flexibility, and disconnects it from relying on Tekton data directly.
> Refactor status handling

- pkg/operator/app/run.go
Previously, "empty" step status values were not being written to the CRD status (although it was not necessary to avoid this extra data, it was just simply extraneous at the time).
Now, however, we need to ensure all steps are represented, even if they are in an "unknown" state, so that we can properly evaluate the success/completion criteria for the run.
> Report unknown step status values

- pkg/entrypoint/runner.go
Processing environment variables (and validating schemas) needs to occur after the when conditions are processed, as now all steps will run concurrently. Otherwise, expression values that are referenced may not be resolvable yet.
Ideally, both Metadata API calls wait until all referenced values are fully resolved, but that can be done later.
> Fix ordering of entrypoint functionality

- pkg/metrics/reconciler/run/reconciler.go
The init time metric sporadically causes false alerts due to a known issue (i.e. the time is being recorded after the message is successfully received by the Metadata API, which may be delayed due to transient connection issues rather than being based off an accurate timestamp sent in the payload).
As this is causing incorrect alerts to be fired (and this is no longer a necessary metric to monitor), this metric is being removed completely.
> Remove init time metric
