- pkg/obj/configmap.go
Right now it's easy for a bad function call that only accepts a parameter to put a run into a completely useless stuck state. This is an artifact of the lack of error propagation on WorkflowRun CRDs mostly, but as a stop-gap we can defer the resolution to step execution. This will at least allow users to see the errors.
CC @kenazk
> Defer invocation resolution to the metadata API

- pkg/obj/job.go
- pkg/obj/persistentvolume.go
- pkg/obj/persistentvolumeclaim.go
- pkg/obj/util.go
Adds underlying, core objects necessary for the custom entrypoint processing.
> Adding core Kubernetes objects for entrypoint handling

- pkg/obj/configmap.go
- pkg/obj/knativeservice.go
- pkg/obj/task.go
- pkg/util/testutil/endtoend.go
- tests/e2e/utils_test.go
- tests/e2e/webhooktrigger_test.go
- tests/e2e/workflowrun_test.go
Adds entrypoint handling (layered on top of the tool injection).
> Initial entrypoint handling

- pkg/operator/reconciler/tenant/reconciler.go
Fixes a (non-impactful) minor defect causing unnecessary requeuing. And an additional safety check, just in case.
> Fix minor issue with volume name

- pkg/operator/reconciler/tenant/reconciler.go
Load the expected volume claim first. This is largely to prevent the tenant ready status from changing back and forth rapidly (in some cases). Also avoids unnecessary processing if the tool injection handling is already configured.
> Ensure proper tenant status

- pkg/metadataapi/server/api/environment.go
- pkg/operator/obj/configmap.go
- pkg/operator/obj/workflowrun.go
- pkg/operator/reconciler/workflow/reconciler.go
Rudimentary, but sufficient until further re-architecture is in place.
> Do not reconcile after user error

- pkg/operator/reconciler/workflow/reconciler.go
This revives old behavior from before a refactor to the operator that selectively applied the Pipeline components depending on the state of the WorkflowRun. This should hopefully reduce churn and lag caused by the Tekton webhook.
> Conditionally apply Pipeline components

- .github/workflows/ci.yaml
- .travis.yml
- hack/containers/registries.conf
- hack/containers/storage.conf
- pkg/workflow/types/v1/decoder_test.go
- pkg/workflow/types/v1/types.go
- pkg/workflow/types/v1/types_test.go
- scripts/build
If anyone knows a better way to do this, **please** let me know.
> Detect explicitly set null literals in parameters

- pkg/operator/reconciler/workflow/reconciler.go
Fixes a regression issue introduced during an upgrade of dependencies.
The original code was introduced to prevent thrashing on unrecoverable user errors, which can have a considerable impact on workflow run processing times.
When this code was changed, it inadvertently reverted this key processing.
Side note: this was caught by examining the linting.
> Fix user error handling during workflow run reconciliation

- .github/workflows/ci.yaml
Update to the latest k3s versions used for testing
> Update to the latest k3s versions used for testing

- manifests/resources/nebula.puppet.com_workflowruns.yaml
- pkg/apis/nebula.puppet.com/v1/types.go
- pkg/apis/nebula.puppet.com/v1/zz_generated.deepcopy.go
- pkg/apis/relay.sh/v1beta1/register.go
- pkg/obj/workflow.go
Add initial Workflow CRD support
> Add initial Workflow CRD support

- manifests/resources/role.yaml
- pkg/install/config/rbac/role.yaml
- pkg/install/controller/operatorstate.go
- pkg/install/controller/relaycorecontroller.go
> Add Workflow CRD RBAC

- pkg/operator/app/configmap.go
- tests/e2e/workflowrun_test.go
* Fixes a few issues with workflow parameters
* Adds additional workflow parameter testing
> Update workflow run parameter handling

- pkg/metadataapi/server/api/conditions.go
- pkg/metadataapi/server/api/conditions_test.go
- pkg/operator/app/condition.go
- pkg/operator/app/run.go
- pkg/operator/handler/condition/run.go
- pkg/operator/handler/condition/step.go
* Basic when condition status information added
* Differentiates between when condition failures and when conditions not satisfied
* Does not include the exact resolution error yet, as that will require substantial changes coming later
* When conditions will no longer wait indefinitely (until timeout) when errors occur
* Updates when condition wait logic to properly handle unresolved when conditions
* This needs a larger refactor in the future
* (i.e. we need to know when something should be resolvable or not at a given point, and we do not have that context right now)
* Code cleanliness and readability improvements 
* More improvements coming later (the condition handlers in particular)
> Adjust when condition error handling

- pkg/operator/app/run.go
Do not use sensitive outputs in status
> Do not use sensitive outputs in status

- pkg/install/app/coredeps.go
When leaving the JWT secret undefined (which should pass through the logic to create the secret and keys), the `Load` method gets called before `ConfigureCoreDefaults`, and was previously failing with a nil pointer exception.
> Handle undefined JWT signing key secret

- pkg/install/reconciler/reconciler.go
- pkg/operator/reconciler/run/reconciler.go
- pkg/operator/reconciler/tenant/reconciler.go
- pkg/operator/reconciler/trigger/reconciler.go
Update reconciler error messages for clarity/consistency
> Update reconciler error messages for clarity/consistency

- pkg/install/app/coredeps.go
- pkg/install/app/vaultconfigdeps.go
- pkg/obj/obj.go
Adds an `IgnoreNilConfigurable` pattern similar to `IgnoreNilPersister`, `IgnoreNilLoader`, etc.
> Add IgnoreNilConfigurable pattern

- go.mod
- go.sum
> Update to latest k8sutil

- cmd/relay-operator-vault-init/main.go
Adds (technically unnecessary) retry logic to the Vault initialization.
Currently, the batch job processing will automatically create new pods to handle this scenario. However, in the standard use-case, Vault will typically not be ready before the initialization jobs start, and therefore the current processing will generally create several pods that Error out before eventually succeeding. As this isn't the most palatable situation, this update shifts the processing to _typically_ succeeding the first time, with the batch job retry processing catching the edge cases instead.
> Add retry/wait logic for vault jobs

- pkg/install/app/admissionregistration.go
During RelayInstaller reconciliation, the `caBundle` data set by the `Webhook Certificate Controller` can be erroneously removed, leading to overall instability of the system and numerous TLS issues (that previously required manually restarting the `Webhook Certificate Controller` to update the proper data again).
> Prevent mutating webhooks from losing caBundle

- manifests/third-party/knative-serving/kustomization.yaml
- pkg/util/testutil/fixtures/knative/3-patch-config.yaml
Enable additional Knative features
> Enable additional Knative features

- pkg/manager/builder/metadata.go
- pkg/manager/configmap/stepmessage.go
- pkg/manager/configmap/stepmessage_test.go
- pkg/manager/reject/stepmessage.go
- pkg/metadataapi/server/api/conditions.go
- pkg/metadataapi/server/api/validate.go
- pkg/metadataapi/server/middleware/auth.go
- pkg/model/model.go
- pkg/model/stepmessage.go
- pkg/operator/app/run.go
Initial implementation of step messages
> Initial implementation of step messages

- pkg/workflow/validation/errors.go
Include cause in validation error message
> Include cause in validation error message

- manifests/installer/install.relay.sh_relaycores.yaml
Minor `generate` change to description.
> Generate latest

- cmd/relay-runtime-tools/main.go
> Fix entrypoint flag check

- pkg/operator/reconciler/run/instrumentation.go
- pkg/operator/reconciler/run/reconciler.go
The "upload log" metrics are in the wrong place currently.
> Fix upload log metrics

- .github/workflows/ci.yaml
- cmd/relay-runtime-tools/main.go
- go.mod
- hack/k3d/registry-config.yaml
- pkg/entrypoint/config.go
- pkg/entrypoint/runner.go
- pkg/entrypoint/runner_test.go
- pkg/model/model.go
- pkg/operator/app/condition.go
- pkg/operator/app/knativeservice.go
- pkg/operator/app/rundeps.go
- pkg/operator/app/task.go
- pkg/operator/app/webhooktriggerdeps.go
- pkg/operator/reconciler/run/reconciler.go
- pkg/operator/reconciler/trigger/reconciler.go
- tests/e2e/e2econfig_test.go
- tests/e2e/run_test.go
Fairly substantial refactor of the Entrypoint logic, as general preparation for upcoming changes.
Some of these changes are _slightly_ opinionated (and therefore subject to further optimizations).
> General entrypoint cleanup/testing

- pkg/entrypoint/runner.go
- pkg/manager/builder/metadata.go
- pkg/manager/configmap/actionstatus.go
- pkg/manager/configmap/actionstatus_test.go
- pkg/manager/memory/actionstatus.go
- pkg/manager/reject/actionstatus.go
- pkg/metadataapi/sample/auth.go
- pkg/metadataapi/server/api/outputs.go
- pkg/metadataapi/server/api/server.go
- pkg/metadataapi/server/api/status.go
- pkg/metadataapi/server/api/status_test.go
- pkg/metadataapi/server/middleware/auth.go
- pkg/model/actionstatus.go
- pkg/model/model.go
Add initial step status handling
> Add initial step status handling

- pkg/operator/app/knativeservice.go
- pkg/operator/app/task.go
Use entrypoint initialize (instead of cp)
> Use entrypoint initialize (instead of cp)

- pkg/manager/configmap/actionstatus.go
- pkg/manager/configmap/actionstatus_test.go
- pkg/metadataapi/server/middleware/auth.go
Temporarily disable the log service for steps
> Temporarily disable the log service for steps

- .ko.yaml
Update `ko` base for runtime tools
> Update ko base for runtime tools

- examples/install/relaycore.yaml
- manifests/installer/install.relay.sh_relaycores.yaml
- manifests/installer/namespace.yaml
- pkg/apis/install.relay.sh/v1alpha1/relaycore_types.go
- pkg/install/app/operatordeps.go
Support automatic creation of the Tenant namespace in the Relay Installer
> Support automatic creation of the Tenant namespace in the Relay Installer

- examples/install/relaycore.yaml
- manifests/installer/install.relay.sh_relaycores.yaml
- pkg/apis/install.relay.sh/v1alpha1/relaycore_types.go
- pkg/apis/install.relay.sh/v1alpha1/zz_generated.deepcopy.go
- pkg/install/app/operator.go
Remove (legacy) log storage volume
> Remove (legacy) log storage volume

- pkg/install/vault/init.go
- pkg/install/vault/policy.go
Update vault config settings to match staging/production.
> Update vault config settings

- pkg/install/app/coredeps.go
Fix small typo to ensure both options for JWT signing keys function correctly.
> Fix JWT signing key support (installer)

- pkg/apis/install.relay.sh/v1alpha1/relaycore_types.go
Add missing `omitempty` options (without this the defaults will not apply correctly under certain circumstances)
> Add missing omitempty options

- manifests/installer/install.relay.sh_relaycores.yaml
- pkg/apis/install.relay.sh/v1alpha1/relaycore_types.go
Cleanup various tags/descriptions/defaults in installer manifest that are out of sync.
> Cleanup tags/descriptions in installer manifest

- pkg/entrypoint/runner.go
- pkg/metadataapi/server/api/status.go
- pkg/model/actionstatus.go
- pkg/operator/handler/condition/step.go
> Refactor failure handling

- pkg/operator/app/run.go
- pkg/operator/handler/condition/run.go
Set failure status based on enhanced step status
> Set failure status based on enhanced step status

- pkg/entrypoint/runner.go
- pkg/operator/app/pipeline.go
Remove Tekton-specific dependency processing
> Remove Tekton-specific dependency processing

- pkg/operator/app/configmap.go
A bit broad of a fix, but focused on resolving the issue at the moment.
> Fix nil panic from evaluation

- pkg/operator/app/run.go
The `Run` start time and completion time are no longer equivalent to the associated `Tekton` `PipelineRun` start and end time.
The `Run` `StartTime` is set to `Now()` initially with the first status update, and the `CompletionTime` is set to the time we transition to an equivalent "completed" status.
This allows this specific logic to disconnect from the underlying `Tekton` data completely and is now only directly associated with `Relay` specific data. The underlying step status values and associated timing information is moving away from `Tekton` specific data shortly, and this is a good initial step in the right direction before that occurs.
Technically these higher level fields could be removed entirely in favor of just using the corresponding status data instead, but preserving …
> Refactor run start/completion time handling

- pkg/entrypoint/runner.go
- pkg/metadataapi/server/api/status.go
- pkg/metadataapi/server/api/status_test.go
- pkg/model/actionstatus.go
Expands the entrypoint action status handling to include timestamps for both the when condition data and the process state data.
> Add timestamps to entrypoint process

- pkg/operator/app/run.go
- pkg/operator/handler/condition/step.go
Disconnects the Relay step status/times from Tekton (and thus the underlying values derived directly from the Pod) in favor of our internal status data we are collecting. This leverages the existing status data (specific to When Condition processing and the final Process State) for now, rather than build in an entirely new set of status data. This sufficiently captures all the data we need for this handling (and is thus convenient at the moment), but it is slightly artificial and would be better served by a more complex change.
> Refactor step status handling

- pkg/operator/app/run.go
Reduce the last remaining Tekton status handling to its most minimal form (it's only being used for the legacy logging, which is also planned for removal).
> Adjust remaining Tekton status handling

- pkg/operator/handler/condition/run.go
- pkg/operator/handler/condition/step.go
Extend the run status and step status handling to account for skipped edge cases.
> Add in additional skipped status handling

- pkg/entrypoint/runner.go
Add signal cancelling for when conditions. This (in conjunction with other recent changes) hardens the cancellation handling and fixes several associated issues that directly impact users.
> Add signal cancelling for when conditions

- pkg/entrypoint/runner.go
Harden entrypoint signal handling for cancellations.
> Harden entrypoint signal handling for cancellations
